"""Add subscription and plan table 

Revision ID: 146ba4ed0e78
Revises: 6706d1861aae
Create Date: 2024-11-16 14:17:42.182632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146ba4ed0e78'
down_revision = '6706d1861aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_table('plan')
    # ### end Alembic commands ###
