"""Add postPhoto url

Revision ID: 1b7e9dbedef7
Revises: 54268d57736f
Create Date: 2024-11-14 14:06:59.108431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7e9dbedef7'
down_revision = '54268d57736f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('post_photo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_photo')
    op.drop_table('post')
    # ### end Alembic commands ###
