"""Add course to education

Revision ID: 54268d57736f
Revises: 8720e7d464cc
Create Date: 2024-11-14 10:34:12.431047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54268d57736f'
down_revision = '8720e7d464cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###
