"""remove ambiguity on post user

Revision ID: a45e4eedd417
Revises: 1b7e9dbedef7
Create Date: 2024-11-15 14:27:08.261525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a45e4eedd417'
down_revision = '1b7e9dbedef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint('post_ibfk_1', type_='foreignkey')
        batch_op.drop_column('approved_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('post_ibfk_1', 'users', ['approved_by'], ['id'])
        batch_op.alter_column('date_posted',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
